andbery_sklad/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(next_page='/'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('',include('sklad_app.urls'))
]

sklad_app/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import *
urlpatterns = [
    path('operation/arrival/', operation_arrival_view, name='operation_arrival'),
    path('operation/departure/', operation_departure_view, name='operation_departure'),
    path('',main,name='main'),
    path('warehouse-statistics/', warehouse_statistics, name='warehouse_statistics'),
    path('warehouseV_statistics/', warehouseV_statistics, name='warehouseV_statistics'),
    path('mbp_statistics/',mbp_statistics,name='mbp_statistics'),
    path('add-pile/', add_pile, name='add_pile'),
    path('ajax/load-brigades/', load_brigades, name='ajax_load_brigades'),
    path('confirm_operations/', confirm_operations, name='confirm_operations'),
    path('get-car-numbers/', get_car_numbers, name='get-car-numbers'),
    path('operation/departure/ajax/load/pile/weight/', load_pile_weight, name='ajax_load_piles_weight'),
    path('operation/departure/ajax/load/car/weight/', load_car_weight, name='ajax_load_cars_weight'),
    path('add_beton/', add_beton, name='add_beton'),
    path('add_wire/', add_wire, name='add_wire'),
    path('add_wire4/', add_wire4, name='add_wire4'),
    path('add_wire6/', add_wire6, name='add_wire6'),
    path('add_armature/', add_armature, name='add_armature'),
    path('add_armature10/', add_armature10, name='add_armature10'),
    path('search/', search_by_date_range, name='search'),
    path('materials_overview/',materials_overview,name='materials_overview'),
    path('prod-class/',classif,name='classes'),
    path('prodV-class/',classifV,name='classesV'),
    path('order/',create_order,name='order'),
    path('add_lists/', add_lists, name='add_lists'),
    path('add_tube/', add_tube, name='add_tube'),
    path('add_tube108/', add_tube108, name='add_tube108'),
    path('add_tube108_2/', add_tube108_2, name='add_tube108_2'),
    path('add_tube133/', add_tube133, name='add_tube133'),
    path('calc_lop/', calculate_lopasti, name='calc_lop'),
    path('materialsV_overview/',materialsV_overview,name='materialsV_overview'),
    path('orders_by_day/',orders_by_day,name='orders_by_day'),
    path('cut_tube/',calculate_tube_cutting,name='cut_tube'),
    path('operation_arrival_list/',operation_arrival_list,name='operation_arrival_list'),
    path('jb/',jb,name='jb'),
    path('vint/',vint,name='vint'),
    path('ware/',ware,name='ware'),
    path('mat/',mat,name='mat'),
    path('export_dep/',export_operation_departures_to_excel,name='export_dep'),
    path('export/operation_arrivals/', export_operation_arrivals_to_excel, name='export_operation_arrivals_to_excel'),
    path('update_mbp/',update_mbp_view,name='update_mbp'),
    path('add_mbp/',add_mbp_view,name='add_mbp'),
    path('order_tube_cutting/',order_tube_cutting,name='order_tube_cutting'),
    path('download-orders/', download_orders, name='download_orders'),
    path('export-material/', export_material_data, name='export_material_data'),
    path('excel/', download_excel, name='excel'),
    path('stat_mbp/', display_mbp_stats, name='stat_mbp'),
    path('latest_deliveries/', latest_deliveries, name='latest_deliveries'),
    path('get_brigades/', get_brigades, name='get_brigades'),
    path('add_debt/', AddDebtView.as_view(), name='add_debt'),
    path('display_debts/', display_debts, name='display_debts'),
    path('process_text_view/', process_text_view, name='process_text_view'),
    path('confirm_operation/', confirm_operation_view, name='confirm_operation'),
    path('update-pile-count/<int:count_id>/', update_pile_count, name='update_pile_count'),
    path('operation-dep-count/', list_operation_dep_count, name='list_operation_dep_count'),
    path('return_piles/', ReturnPilesView.as_view(), name='return_piles'),
    path('return_piles_list/', ReturnPilesListView.as_view(), name='return_piles_list'),
    path('confirm_sklad_list/', ConfirmSkladView.as_view(), name='confirm_sklad_list'),
    path('debts/', DebtListView.as_view(), name='debt_list'),
    path('debts/<int:brigade_id>/', DebtDetailView.as_view(), name='debt_detail'),
    path('confirm_departures/', confirm_departures_view, name='confirm_departures'),
    path('update_send_operation/<int:operation_id>/', update_send_operation, name='update_send_operation'),
    path('add_pile_to_count/<int:count_id>/', add_pile_to_count, name='add_pile_to_count'),
    path('tool-operation-list/', ToolOperationListView.as_view(), name='tool_operation_list'),
    path('get-brigade-tools/<int:brigade_id>/', get_brigade_tools, name='get_brigade_tools'),
    path('tool-operation/', ToolOperationView.as_view(), name='tool_operation_form'),
    path('export-tool-details/', ExportToolDetailsView.as_view(), name='export_tool_details'),
]

sklad_app/forms.py
from .models import OperationArrival, BrigadeWork, Car
from django import forms
from .models import OperationDeparture, NamePile, Pile, ReturnPile
from .models import *


class BetonForm(forms.ModelForm):
    class Meta:
        model = Beton
        exclude = ['date']  # Исключаем поле даты
        labels = {
            'count': 'Количество в куб',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Цена за куб',
        }

class WireForm(forms.ModelForm):
    class Meta:
        model = Wire
        exclude = ['date']  # Исключаем поле даты
        labels = {
            'count': 'Количество',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Цена за кг',
        }
class WireForm4(forms.ModelForm):
    class Meta:
        model = Wire4
        exclude = ['date']  # Исключаем поле даты
        labels = {
            'count': 'Количество',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Цена за кг',
        }
class WireForm6(forms.ModelForm):
    class Meta:
        model = Wire6
        exclude = ['date']  # Исключаем поле даты
        labels = {
            'count': 'Количество',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Цена за кг',
        }
class ArmatureForm(forms.ModelForm):
    class Meta:
        model = Armature
        exclude = ['date']  # Исключаем поле даты
        labels = {
            'count': 'Количество в кг',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Цена за кг',
        }
class Armature10Form(forms.ModelForm):
    class Meta:
        model = Armature10
        exclude = ['date']  # Исключаем поле даты
        labels = {
            'count': 'Количество в кг',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Цена за кг',
        }

#class OperationArrivalForm(forms.ModelForm):
#    name_pile = forms.ModelChoiceField(queryset=NamePile.objects.all(), label="Название сваи", required=True)
#
#    class Meta:
 #       model = OperationArrival
 #       fields = ['name_pile', 'pile', 'quantity', 'description', 'brigade']
  #      labels = {
   #         'name_pile': 'Название сваи',
    #        'pile': 'Свая',
    #        'quantity': 'Количество',
     #       'description': 'Описание (если требуется)',
      #      'brigade': 'Бригада',
       # }
        #widgets = {
    #        'name_pile': forms.Select(attrs={'class': 'name_pile'}),
     #       'pile': forms.Select(attrs={'class': 'pile'}),
      #  }

#    def __init__(self, *args, **kwargs):
 #       super(OperationArrivalForm, self).__init__(*args, **kwargs)
  #      self.fields['pile'].queryset = Pile.objects.none()
#
 #       if 'name_pile' in self.data:
  #          try:
   #             name_pile_id = int(self.data.get('name_pile'))
    #            self.fields['pile'].queryset = Pile.objects.filter(name_id=name_pile_id).order_by('name')
     #       except (ValueError, TypeError):
      #          pass  # invalid input from the client; ignore and fallback to empty City queryset
       # elif self.instance.pk:
        #    self.fields['pile'].queryset = self.instance.name_pile.pile_set.order_by('name')






class SearchForm(forms.Form):
    manager = forms.CharField(max_length=500, required=False, label='Лид')
    date_from = forms.DateField(required=False, label='Дата с', widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(required=False, label='Дата по', widget=forms.DateInput(attrs={'type': 'date'}))
    brigade = forms.ModelChoiceField(queryset=BrigadeWork.objects.all(), required=False, empty_label="Все бригады",label='Бригада')


class NamePileAndPileForm(forms.Form):
    name = forms.CharField(max_length=232, label="Название")
    pile_type = forms.ChoiceField(choices=NamePile.TYPE_CHOICES, label="Тип")
    size = forms.CharField(max_length=100, label="Размер")
    count = forms.IntegerField(label="Количество")
    defect = forms.IntegerField(label="Дефекты")

    def save(self):
        name_pile_data = {
            'name': self.cleaned_data['name'],
            'pile_type': self.cleaned_data['pile_type']
        }
        name_pile = NamePile.objects.create(**name_pile_data)

        pile_data = {
            'name': name_pile,
            'size': self.cleaned_data['size'],
            'count': self.cleaned_data['count'],
            'defect': self.cleaned_data['defect']
        }
        Pile.objects.create(**pile_data)


class DateRangeForm(forms.Form):
    date_from = forms.DateField(required=False, label='Дата с', widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(required=False, label='Дата по', widget=forms.DateInput(attrs={'type': 'date'}))




class TubeForm(forms.ModelForm):
    class Meta:
        model = Tube
        exclude = ['date','unit_price']
        labels = {
            'count': 'Кг 89 трубы',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Стоимость',
        }
class TubeForm108(forms.ModelForm):
    class Meta:
        model = Tube108
        exclude = ['date','unit_price']  # Исключаем поле даты
        labels = {
            'count': 'Кг 108 трубы',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Стоимость',
        }
class TubeForm108_2(forms.ModelForm):
    class Meta:
        model = Tube108_2
        exclude = ['date','unit_price']
        labels = {
            'count': 'Кг 108*3.5 трубы',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Стоимость',
        }
class TubeForm133(forms.ModelForm):
    class Meta:
        model = Tube133
        exclude = ['date','unit_price']
        labels = {
            'count': 'Кг 133 трубы',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Стоимость',
        }
class ListForm(forms.ModelForm):
    class Meta:
        model = Lists
        fields = ['count', 'company_sell', 'company_buy', 'price']
        labels = {
            'count': 'Количество',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Цена',
        }

class List5Form(forms.ModelForm):
    class Meta:
        model = Lists5
        fields = ['count', 'company_sell', 'company_buy', 'price']
        labels = {
            'count': 'Количество',
            'company_sell': 'Компания-продавец',
            'company_buy': 'Компания-покупатель',
            'price': 'Цена',
        }

class ExportForm(forms.Form):
    date_from = forms.DateField(label='Дата с', widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(label='Дата по', widget=forms.DateInput(attrs={'type': 'date'}))
    brigade = forms.ModelChoiceField(label='Бригада', queryset=BrigadeWork.objects.all(), required=False)

class ExportArrForm(forms.Form):
    date_from = forms.DateField(label='Дата с', widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(label='Дата по', widget=forms.DateInput(attrs={'type': 'date'}))
    brigade = forms.ModelChoiceField(label='Бригада', queryset=Brigade.objects.all(), required=False)

from django.forms import ModelChoiceField, DateField

class MaterialExportForm(forms.Form):
    MATERIAL_CHOICES = [
        ('beton', 'Бетон'),
        ('wire', 'Проволка 3мм'),
        ('wire4', 'Проволка 4мм'),
        ('wire6', 'Проволка 6мм'),
        ('armature', 'Арматура 8мм'),
        ('armature10', 'Арматура 10мм')
    ]
    material = forms.ChoiceField(choices=MATERIAL_CHOICES, label="Select Material")
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label="From")
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label="To")

class TextProcessingForm(forms.Form):
    text_input = forms.CharField(label='Введите смс', widget=forms.Textarea)
    brigade = forms.ModelChoiceField(queryset=BrigadeWork.objects.all(), label='Выберите бригаду', required=False)

class AddPileForm(forms.Form):
    pile = forms.ChoiceField(label='Выберите сваю')
    quantity = forms.IntegerField(label='Количество', min_value=1)

class ToolOperationForm(forms.Form):
    brigade = forms.ModelChoiceField(queryset=BrigadeWork.objects.all(), label='Выберите бригаду')
    operation = forms.ChoiceField(choices=[('Списать', 'Списать'), ('Дать', 'Дать')], label='Выберите операцию')

    def __init__(self, *args, **kwargs):
        super(ToolOperationForm, self).__init__(*args, **kwargs)
        tools = Tool.objects.all()
        for tool in tools:
            self.fields[f'tool_{tool.id}'] = forms.IntegerField(label=f'{tool.name}', min_value=0, required=False)

class DateRangeForm(forms.Form):
    start_date = forms.DateField(label='Дата начала', widget=forms.TextInput(attrs={'type': 'date'}))
    end_date = forms.DateField(label='Дата окончания', required=False, widget=forms.TextInput(attrs={'type': 'date'}))

templates/add_beton.html
{% extends "index.html" %}
{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
    }

    h2 {
        text-align: center;
        color: #333;
    }

    form {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input[type="text"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button[type="submit"] {
        background-color: #e30b0b;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }

    button[type="submit"]:hover {
        background-color: #ad3939;
    }

    .form-group select {
        display: block;
        width: 100%;
    }
</style>
<h2>Прибытие бетона</h2>
<a href="{% url 'classes' %}" class="button">Назад</a>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
    </div>
    <button type="submit">Сохранить</button>
</form>
{%endblock%}

templates/add_wire.html
{% extends "index.html" %}
{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
    }

    h2 {
        text-align: center;
        color: #333;
    }

    form {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input[type="text"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button[type="submit"] {
        background-color: #e30b0b;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }

    button[type="submit"]:hover {
        background-color: #ad3939;
    }

    .form-group select {
        display: block;
        width: 100%;
    }
</style>
<h2>Прибытие проволки {{size}}</h2>
<a href="{% url 'classes' %}" class="button">Назад</a>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
    </div>
    <button type="submit">Сохранить</button>
</form>
{%endblock%}

templates/classes_v.html
{% extends "index.html" %}

{% block content %}
<style>
    .button {
    display: inline-block;
    margin: 10px;
    padding: 10px 20px;
    background-image: linear-gradient(to right, #f44336, #d32f2f); /* Градиентный фон */
    color: white;
    text-decoration: none;
    border: none; /* Убираем стандартную рамку */
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2); /* Добавляем тень для эффекта глубины */
    transition: all 0.3s ease; /* Плавные переходы для фона, тени и трансформации */
}

    .button:hover {
    background-image: linear-gradient(to right, #d32f2f, #b71c1c); /* Изменение градиента при наведении */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Увеличение тени для "поднятия" кнопки */
    transform: translateY(-2px); /* Поднимаем кнопку при наведении */
}
</style>
<a href="{% url 'vint' %}" class="button">Назад</a>
<h3>Прибытие материалов</h3>
        <div class="buttons-container">
            {% if user.is_authenticated and user.userprofile.role.name == "Производство" %}
                <a href="{% url 'calc_lop' %}" class="button">Производство лопастей</a>
                <a href="{% url 'add_tube' %}" class="button">Труба 89мм</a>
                <a href="{% url 'add_tube108' %}" class="button">Труба 108мм</a>
                <a href="{% url 'add_tube108_2' %}" class="button">Труба 108мм 3.5</a>
                <a href="{% url 'add_tube133' %}" class="button">Труба 133мм</a>
                <a href="{% url 'add_lists' %}" class="button">Прибытие листов</a>
            {%endif%}
        </div>
{% endblock %}

templates/create_order.html
{% extends "index.html" %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
    }

    h2 {
        text-align: center;
        color: #333;
    }

    form {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input[type="text"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button[type="submit"] {
        background-color: #e30b0b;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }

    button[type="submit"]:hover {
        background-color: #ad3939;
    }

    .form-group select {
        display: block;
        width: 100%;
    }
</style>
    <h1>Создание разнарядки</h1>

    <a href="{% url 'jb' %}" class="button">Назад</a>
    <form action="" method="post">
        {% csrf_token %}
        {% for pile in piles %}
        <div>
            <label for="pile_{{forloop.counter}}">{{ pile.name.name }} {{ pile.size }}</label>
            <input type="number" id="pile_{{forloop.counter}}" name="pile_{{pile.id}}" min="0" value="" placeholder="Кол-во форм">
        </div>
        {% endfor %}
        <button type="submit">Сохранить</button>
    </form>
{%endblock%}

templates/debt_list.html
{% extends "index.html" %}

{% block content %}
<h2>Список бригад</h2>
<ul>
    {% for brigade in brigades %}
    <li>
        <a href="{% url 'debt_detail' brigade.id %}">{{ brigade.name }}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/export_form.html
{% extends 'index.html' %}

{% block content %}
<h2>Экспорт операций отгрузки</h2>
<form method="post" action="{% url 'export_dep' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Экспорт в Excel</button>
</form>
{% endblock %}

templates/lopasti_calculation.html
{% extends 'index.html' %}

{% block content %}
<style>
    form {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }
    div {
        margin-bottom: 10px;
    }
    label {
        display: inline-block;
        margin-bottom: 5px;
        font-weight: bold;
    }
    input[type="number"] {
        width: 100%;
        padding: 10px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }
    input[type="number"]:focus {
        background-color: #ddd;
        outline: none;
    }
    button[type="submit"] {
        background-color: #a31717;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }
    button[type="submit"]:hover {
        opacity:1;
    }
</style>

  <form method="post">
        {% csrf_token %}
        <label for="thickness">Выберите толщину листа:</label>
        <select name="thickness" id="thickness">
            <option value="4">4 мм</option>
            <option value="5">5 мм</option>
        </select>

        <h2>Введите количество листов для каждого диаметра:</h2>
        {% for diameter in diameters %}
        <div>
            <label for="diameter_{{ diameter }}">Листы {{ diameter }} диаметр (мм):</label>
            <input type="number" name="{{ diameter }}" id="diameter_{{ diameter }}" min="0" value="0">
        </div>
        {% endfor %}

        <button type="submit">Рассчитать</button>
    </form>
{% endblock %}

templates/operation_arrival.html
{% extends "index.html" %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<style>
    body {
        font-family: Arial, sans-serif;
    }

    h2 {
        text-align: center;
        color: #333;
    }

    form {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input[type="text"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button[type="submit"] {
        background-color: #e30b0b;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }

    button[type="submit"]:hover {
        background-color: #ad3939;
    }

    .form-group select {
        display: block;
        width: 100%;
    }
    .button {
    display: inline-block;
    margin: 10px;
    padding: 10px 20px;
    background-image: linear-gradient(to right, #f44336, #d32f2f); /* Градиентный фон */
    color: white;
    text-decoration: none;
    border: none; /* Убираем стандартную рамку */
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2); /* Добавляем тень для эффекта глубины */
    transition: all 0.3s ease; /* Плавные переходы для фона, тени и трансформации */
}
</style>
<script>
$(document).ready(function() {
  $('#id_name_pile').change(function() {  // Обратите внимание на правильный ID для вашего поля выбора NamePile
    var url = $('#operationArrivalForm').attr('data-piles-url');  // Получаем URL из атрибута data-piles-url формы
    var namePileId = $(this).val();  // Получаем выбранный ID NamePile

    $.ajax({
      url: url,
      data: {
        'name_pile_id': namePileId  // Передаем ID в запросе
      },
      success: function (data) {
        $("#id_pile").html('');  // Очищаем текущие опции
        data.forEach(function (pile) {
          $("#id_pile").append(`<option value="${pile.id}">${pile.size}</option>`);  // Добавляем новые опции
        });
      }
    });
  });
});
</script>
<script>
$(document).ready(function() {

  $('#id_quantity').addClass('required-field');
  $('#id_defect').addClass('required-field');
  $('#id_brigade').addClass('required-field');



  function checkFormFields() {
    var allFilled = true;
    $('.required-field').each(function() {
      if ($(this).val() === '') {
        allFilled = false;
        return false; // Выход из цикла
      }
    });


    $('form#operationArrivalForm button[type="submit"]').prop('disabled', !allFilled);
  }


  $(document).on('change keyup', '.required-field', checkFormFields);


  checkFormFields();
});
</script>
<h2>Производство свай</h2>
<a href="{% url 'jb' %}" class="button">Назад</a>
<form action="" method="post">
    {% csrf_token %}
    <div>
        <label for="brigade">Бригада:</label>
        <select id="brigade" name="brigade">
            {% for brigade in brigades %}
            <option value="{{ brigade.id }}">{{ brigade.name }}</option>
            {% endfor %}
        </select>
    </div>
    <p>Введите количество форм:</p>
    {% for pile in piles %}
    <div class="pile-input">
        <label for="pile_{{ pile.id }}">{{ pile.name.name }} {{ pile.size }}</label>
        <input type="number" id="pile_{{ pile.id }}" name="pile_{{ pile.id }}" min="0" value="" placeholder="Кол-во форм">
    </div>
    {% endfor %}
    <button type="submit">Сохранить</button>
</form>
{%endblock%}

templates/return_piles_list.html
{% extends "index.html" %}

{% block content %}
<a href="/" class="button">Назад</a>
<h2>Возврат свай</h2>
<table>
    <thead>
        <tr>
            <th>Дата</th>
            <th>Бригада</th>
            <th>Описание</th>
            <th>Детали</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
        {% for return_pile in return_piles_list %}
        <tr>
            <td>{{ return_pile.date|date:"d.m.Y H:i" }}</td>
            <td>{{ return_pile.brigade.name }}</td>
            <td>{{ return_pile.description }}</td>
            <td>
                {% for detail in return_pile.details_dict.values %}
                <div>{{ detail.name }} {{ detail.size }}: {{ detail.quantity }}</div>
                {% endfor %}
            </td>
            <td>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="return_pile_id" value="{{ return_pile.id }}">
                    <button type="submit">Подтвердить</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}